services:
  django:
    build:
      context: .
      dockerfile: ./docker/django.Dockerfile
    env_file:
      - .env
    volumes:
      - media_volume:/app/mediafiles
      - ./staticfiles:/app/staticfiles

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    depends_on:
      - django


volumes:
  media_volume:
