services:
  
  django:
    build:
      context: .
      dockerfile: ./docker/django.Dockerfile
    container_name: django
    command: gunicorn PyCrypt.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - media_volume:/app/mediafiles
      - static_volume:/app/staticfiles

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
    depends_on:
      - django
  
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  
  celery:
    build:
      context: .
      dockerfile: ./docker/django.Dockerfile
    container_name: celery
    command: celery -A PyCrypt worker -l info
    env_file:
      - .env
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - django
      - redis


volumes:
  media_volume:
  static_volume:
